import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

const ENV_FILE = path.join("env", ".env.git.local");

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    encoding: "utf8",
    ...options,
  });

  if (result.error) {
    throw new Error(`Failed to run ${command}: ${result.error.message}`);
  }

  if (result.status !== 0) {
    const stderr = (result.stderr || "").trim();
    throw new Error(stderr || `${command} exited with status ${result.status}`);
  }

  return (result.stdout || "").trim();
}

function normalizeRepoPath(remoteUrl) {
  if (!remoteUrl) {
    return { owner: "", projectName: "" };
  }

  // Supports git@github.com:owner/repo.git and https://github.com/owner/repo.git
  const sshMatch = remoteUrl.match(/^[^@]+@[^:]+:([^/]+)\/([^/]+?)(?:\.git)?$/i);
  if (sshMatch) {
    return {
      owner: sshMatch[1].toLowerCase(),
      projectName: sshMatch[2].toLowerCase(),
    };
  }

  const httpMatch = remoteUrl.match(/^[a-z]+:\/\/[^/]+\/([^/]+)\/([^/]+?)(?:\.git)?$/i);
  if (httpMatch) {
    return {
      owner: httpMatch[1].toLowerCase(),
      projectName: httpMatch[2].toLowerCase(),
    };
  }

  return { owner: "", projectName: "" };
}

function main() {
  console.log(`  -> Regenerating local environment file based on git info ${ENV_FILE}`);

  const remoteUrl = run("git", ["remote", "get-url", "origin"]);
  const { owner, projectName } = normalizeRepoPath(remoteUrl);
  const hash = run("git", ["rev-parse", "--short", "HEAD"]).toLowerCase();
  const branch = run("git", ["rev-parse", "--abbrev-ref", "HEAD"]).toLowerCase();
  const lastMsg = run("git", ["log", "-1", "--pretty=%s"]);

  const codenamizeOutput = run("node", ["scripts/codenamize.cjs", `/${owner}/${projectName}/${branch}`]);
  const codeName = codenamizeOutput.split(/\r?\n/).pop() || "";

  const envLines = [
    "# DO NOT EDIT THIS FILE IT IS AUTOMATICALLY GENERATED",
    "# this file is automatically generated by the post-commit hook (see scripts/generate_git_env).",
    "",
    `VITE_PROJECT_NAME          = ${projectName}`,
    `VITE_GIT_HASH              = ${hash}`,
    "VITE_GIT_REPO_NAME         = ${VITE_PROJECT_NAME}",
    `VITE_GIT_OWNER             = ${owner}`,
    `VITE_GIT_BRANCH_NAME       = ${branch}`,
    'VITE_DEPLOY_BASE_PATH      =  "/${VITE_GIT_OWNER}/${VITE_GIT_REPO_NAME}/${VITE_GIT_BRANCH_NAME}/"',
    `VITE_CODE_NAME             = ${codeName}`,
    `VITE_GIT_LAST_MSG          = ${lastMsg}`,
    "",
    "# this port might not be correct, but it doesn't really matter",
  ];

  const isDefaultSmileRepo = owner === "nyuccl" && projectName === "smile";
  envLines.push(`VITE_DEV_PORT_NUM          =  ${isDefaultSmileRepo ? "3000" : "3020"}`);
  envLines.push('VITE_DEPLOY_URL            =  "http://localhost:${VITE_DEV_PORT_NUM}${VITE_DEPLOY_BASE_PATH}"');
  envLines.push('VITE_CODE_NAME_DEPLOY_URL  =  "http://localhost:${VITE_DEV_PORT_NUM}/e/${VITE_CODE_NAME}"');

  fs.mkdirSync(path.dirname(ENV_FILE), { recursive: true });
  fs.writeFileSync(ENV_FILE, `${envLines.join("\n")}\n`, "utf8");
}

try {
  main();
} catch (error) {
  console.error(error.message);
  process.exit(1);
}
