name: Build and Deploy

on:
  workflow_call:
    inputs:
      node_version:
        description: 'The version of Node.js to use'
        required: true
        type: string
    secrets:
      SECRET_APP_CONFIG:
        required: true
      EXP_DEPLOY_PATH:
        required: true
      EXP_DEPLOY_HOST:
        required: true
      EXP_DEPLOY_USER:
        required: true
      EXP_DEPLOY_KEY:
        required: true
      EXP_DEPLOY_PORT:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install Node Dependencies
        run: npm install
