# This is a basic workflow to deploy your smile experiment

name: DEPLOY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches-ignore:
      - analysis # want this to be all branches eventually
      - models
      - docs
    paths-ignore: # ignore any changes to the docs for this workflow or unimportant files
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkout_code:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      ## TODO CHANGE THIS TO CHECK OUT THE BRANCH THAT WAS COMMITTED TO
      - name: Checkout code commited to branch
        uses: actions/checkout@v4
  
  build_and_deploy:
    needs: checkout_code
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      node_version: '20.11.1'
    secrets:
      SECRET_APP_CONFIG: ${{ secrets.SECRET_APP_CONFIG }}
      EXP_DEPLOY_PATH: ${{ secrets.EXP_DEPLOY_PATH }}
      EXP_DEPLOY_HOST: ${{ secrets.EXP_DEPLOY_HOST }}
      EXP_DEPLOY_USER: ${{ secrets.EXP_DEPLOY_USER }}
      EXP_DEPLOY_KEY: ${{ secrets.EXP_DEPLOY_KEY }}
      EXP_DEPLOY_PORT: ${{ secrets.EXP_DEPLOY_PORT }}
      EXP_DEPLOY_PATH: ${{ secrets.EXP_DEPLOY_PATH }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

