name: Format and Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  format-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        id: prettier-check
        run: npx prettier --check . || echo "PRETTIER_FAILED=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: Format code with Prettier
        if: env.PRETTIER_FAILED == 'true'
        run: npx prettier --write .

      - name: Commit formatting changes
        if: env.PRETTIER_FAILED == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: apply prettier formatting'
          branch: ${{ github.head_ref }}

      - name: Run tests
        id: run-tests
        run: npm run test
        continue-on-error: true

      - name: Report test status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const prettier_failed = process.env.PRETTIER_FAILED === 'true';
            const tests_failed = "${{ steps.run-tests.outcome }}" === "failure";

            let summary = "## Format and Test Results\n\n";

            if (prettier_failed) {
              summary += "⚠️ **Code formatting issues detected and fixed**\n\n";
              summary += "Prettier has automatically formatted your code according to the project's style guidelines. The changes have been committed to your branch.\n\n";
            } else {
              summary += "✅ **Code formatting looks good!**\n\n";
            }

            if (tests_failed) {
              summary += "❌ **Tests failed**\n\n";
              summary += "Please check the workflow logs for details on the failing tests.\n\n";
            } else {
              summary += "✅ **All tests passed!**\n\n";
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });

            if (tests_failed) {
              core.setFailed("Tests failed. Please fix the failing tests before merging.");
            }
